# Generated by Django 2.2.4 on 2019-10-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=150)),
                ('wx_oppid', models.CharField(max_length=150)),
                ('ali_oppid', models.CharField(max_length=150)),
                ('qq_oppid', models.CharField(max_length=150)),
                ('git_hub_oppid', models.CharField(max_length=150)),
                ('last_login', models.DateField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
