# Generated by Django 2.1.7 on 2019-07-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0001_update_honor_goodsclass_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsclass',
            name='created_at',
            field=models.DateTimeField(help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='goodsclass',
            name='is_show',
            field=models.IntegerField(default=1, help_text='商品展示开关'),
        ),
        migrations.AlterField(
            model_name='goodsclass',
            name='name',
            field=models.CharField(help_text='分类名称', max_length=15),
        ),
        migrations.AlterField(
            model_name='goodsclass',
            name='parent_id',
            field=models.IntegerField(help_text='商品所属父类id,顶级分类为0'),
        ),
        migrations.AlterField(
            model_name='goodsclass',
            name='sort',
            field=models.SmallIntegerField(help_text='同级分类权重'),
        ),
        migrations.AlterField(
            model_name='goodsclass',
            name='updated_at',
            field=models.DateTimeField(help_text='更新时间'),
        ),
    ]
