# Generated by Django 2.1.7 on 2019-07-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0002_auto_20190702_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsclass',
            name='is_show',
            field=models.IntegerField(default=1),
        ),
    ]
