# Generated by Django 2.1.7 on 2019-07-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0003_add_honor_goods_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsclass',
            name='parent_id',
            field=models.IntegerField(default=0, help_text='父级id'),
        ),
    ]
