# Generated by Django 2.1.7 on 2019-07-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0007_alter_honor_goods_class_column_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='class_id',
            new_name='goodclass',
        ),
    ]
