# Generated by Django 2.1.7 on 2019-07-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0009_add_factory_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goods',
            new_name='factory',
        ),
    ]
