# Generated by Django 2.1.7 on 2019-07-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0011_add_demo_model_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
        migrations.AlterModelTable(
            name='factory',
            table='honor_factory',
        ),
        migrations.AlterModelTable(
            name='goods',
            table='honor_goods',
        ),
        migrations.AlterModelTable(
            name='goodsclass',
            table='honor_goods_class',
        ),
        migrations.AlterModelTable(
            name='goodsfactory',
            table='goods_factory',
        ),
    ]
