# Generated by Django 2.1.7 on 2019-07-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0008_alter_honor_goods_class_column_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='厂家名字', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsFactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('factory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honor.Factory')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honor.Goods')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goods',
            field=models.ManyToManyField(through='honor.GoodsFactory', to='honor.Factory'),
        ),
    ]
