# Generated by Django 2.1.7 on 2019-07-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='分类名称')),
                ('is_show', models.IntegerField(default=1, verbose_name='商品展示开关')),
                ('parent_id', models.IntegerField(verbose_name='商品所属父类id,顶级分类为0')),
                ('sort', models.SmallIntegerField(verbose_name='同级分类权重')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
