# Generated by Django 2.1.7 on 2019-07-07 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0002_update_honor_goodsclass_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='商品名称', max_length=100)),
                ('price', models.IntegerField(help_text='商品价格')),
                ('stock', models.IntegerField(help_text='商品库存')),
                ('desc', models.CharField(help_text='商品描述', max_length=255)),
                ('head_img', models.CharField(help_text='商品主图路径', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='goodsclass',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='goods',
            name='class_id',
            field=models.ForeignKey(help_text='所属分类', on_delete=django.db.models.deletion.CASCADE, to='honor.GoodsClass'),
        ),
    ]
