# Generated by Django 2.1.7 on 2019-07-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0004_alter_honor_goods_class_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='head_img',
            field=models.CharField(default='', help_text='商品主图路径', max_length=255),
        ),
    ]
