# Generated by Django 2.1.7 on 2019-07-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0010_alter_goods_model_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'demo',
            },
        ),
    ]
